title: Lori A. Berberian
description: Using satellite time series to build a history-only baseline for Californiaâ€™s kelp forests
logo: /assets/IMG/image.png
show_downloads: false
theme: jekyll-theme-cayman
